ALTER TABLE [dbo].[TS_MARK]
ADD CONSTRAINT [TS_MARK_fk] FOREIGN KEY ([TS_TP]) 
  REFERENCES [dbo].[TS_TYPE] ([ID_TTS]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[PAY]
ADD CONSTRAINT [PAY_CUST_fk] FOREIGN KEY ([ID_CUST]) 
  REFERENCES [dbo].[CUST] ([IIN]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[PAY]
ADD CONSTRAINT [PAY_fk] FOREIGN KEY ([ID_WORKER]) 
  REFERENCES [dbo].[TS_WORKER] ([ID_WORKER]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[TS_SUB]
ADD CONSTRAINT [TS_SUB_fk] FOREIGN KEY ([IDWORKER]) 
  REFERENCES [dbo].[TS_WORKER] ([ID_WORKER]) 
  ON UPDATE  SET NULL
  ON DELETE  SET NULL
GO

ALTER TABLE [dbo].[SZAKAZ]
ADD CONSTRAINT [SZAKAZ_SERVICE_fk] FOREIGN KEY ([ID_ZAKAZ]) 
  REFERENCES [dbo].[SERVICE] ([ID_SERV]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[SZAKAZ]
ADD CONSTRAINT [SZAKAZ_WORKER_fk] FOREIGN KEY ([ID_WORKER]) 
  REFERENCES [dbo].[TS_WORKER] ([ID_WORKER]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[UZAKAZ]
ADD CONSTRAINT [UZAKAZ_SCLAD_fk] FOREIGN KEY ([ID_SCLAD]) 
  REFERENCES [dbo].[SCLAD] ([ID_SC]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[UZAKAZ]
ADD CONSTRAINT [UZAKAZ_WORKER_fk] FOREIGN KEY ([ID_WORKER]) 
  REFERENCES [dbo].[TS_WORKER] ([ID_WORKER]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[UZAKAZ]
ADD CONSTRAINT [UZAKAZ_ZAKAZ_fk] FOREIGN KEY ([ID_ZAKAZ]) 
  REFERENCES [dbo].[ZAKAZ] ([ID_ZAKAZ]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[TS_WORKER]
ADD CONSTRAINT [TS_WORKER_fk] FOREIGN KEY ([ID_SUB]) 
  REFERENCES [dbo].[TS_SUB] ([ID_SUB]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[ZAKAZ]
ADD CONSTRAINT [ZAKAZ_CUST_fk] FOREIGN KEY ([ID_CUST]) 
  REFERENCES [dbo].[CUST] ([IIN]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[ZAKAZ]
ADD CONSTRAINT [ZAKAZ_TS_fk] FOREIGN KEY ([ID_TS]) 
  REFERENCES [dbo].[TS_TYPE] ([ID_TTS]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[ZAKAZ]
ADD CONSTRAINT [ZAKAZ_TS_MARK_fk] FOREIGN KEY ([ID_TSMARK]) 
  REFERENCES [dbo].[TS_MARK] ([ID_TTS]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO

ALTER TABLE [dbo].[PAY]
ADD CONSTRAINT [PAY_ZAKAZ_fk] FOREIGN KEY ([ID_ZAKAZA]) 
  REFERENCES [dbo].[ZAKAZ] ([ID_ZAKAZ]) 
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
GO
