CREATE TABLE [dbo].[CUST] (
  [IIN] bigint NOT NULL,
  [NAME] varchar(50) NOT NULL,
  [SECNAME] varchar(50) NOT NULL,
  [LASTNAME] varchar(50) NOT NULL,
  [COUNTRY] varchar(50) NOT NULL,
  [CITY] varchar(50) NOT NULL,
  [STREET] varchar(50) NOT NULL,
  [HOME] varchar(100) NOT NULL,
  [PHONE] varchar(20) NOT NULL,
  PRIMARY KEY CLUSTERED ([IIN])
)
GO

CREATE TABLE [dbo].[PAY] (
  [ID_OPLATA] int IDENTITY(1, 1) NOT NULL,
  [DATA] date NOT NULL,
  [ID_ZAKAZA] int NOT NULL,
  [ID_CUST] bigint NOT NULL,
  [ID_WORKER] int NOT NULL,
  [PRICE] int NOT NULL,
  PRIMARY KEY CLUSTERED ([ID_OPLATA])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[SCLAD] (
  [ID_SC] int IDENTITY(1, 1) NOT NULL,
  [NAME] varchar(200) NOT NULL,
  [TYPES] varchar(50) NOT NULL,
  [CNAME] varchar(10) NOT NULL,
  [PRICE] int NOT NULL,
  [COUNT] int NOT NULL,
  PRIMARY KEY CLUSTERED ([ID_SC])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[SERVICE] (
  [ID_SERV] int IDENTITY(1, 1) NOT NULL,
  [NAME] varchar(200) NOT NULL,
  [PRICE] int NULL,
  PRIMARY KEY CLUSTERED ([ID_SERV])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[TS_SUB] (
  [ID_SUB] int IDENTITY(1, 1) NOT NULL,
  [NAME] varchar(200) NOT NULL,
  [IDWORKER] int ,
  PRIMARY KEY CLUSTERED ([ID_SUB])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[SZAKAZ] (
  [ID_ZUSLUG] int IDENTITY(1, 1) NOT NULL,
  [ID_ZAKAZ] int NOT NULL,
  [ID_WORKER] int NOT NULL,
  PRIMARY KEY CLUSTERED ([ID_ZUSLUG])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[TS_MARK] (
  [ID_TTS] int IDENTITY(1, 1) NOT NULL,
  [TS_NAME] varchar(100) NOT NULL,
  [TS_TP] int NULL,
  PRIMARY KEY CLUSTERED ([ID_TTS])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[TS_TYPE] (
  [ID_TTS] int IDENTITY(1, 1) NOT NULL,
  [TS_NAME] varchar(100) NOT NULL,
  PRIMARY KEY CLUSTERED ([ID_TTS])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[UZAKAZ] (
  [ID_RESURCE] int IDENTITY(1, 1) NOT NULL,
  [ID_ZAKAZ] int NOT NULL,
  [ID_SCLAD] int NOT NULL,
  [COUNTS] int NULL,
  [ID_WORKER] int NULL,
  PRIMARY KEY CLUSTERED ([ID_RESURCE])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[TS_WORKER] (
  [ID_WORKER] int IDENTITY(1, 1) NOT NULL,
  [NAME] varchar(50) NOT NULL,
  [SECNAME] varchar(50) NOT NULL,
  [LASNAME] varchar(50) NOT NULL,
  [ID_SUB] int NOT NULL,
  [STATUS] varchar(100) NOT NULL,
  PRIMARY KEY CLUSTERED ([ID_WORKER])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[ZAKAZ] (
  [ID_ZAKAZ] int IDENTITY(1, 1) NOT NULL,
  [ID_CUST] bigint NOT NULL,
  [DATA] date NOT NULL,
  [ID_TSMARK] int NOT NULL,
  [ID_TS] int NOT NULL,
  [TSINFO] text NULL,
  [EDATA] date NULL,
  PRIMARY KEY CLUSTERED ([ID_ZAKAZ])
)
ON [PRIMARY]
GO