CREATE TABLE [dbo].[PAY] (
  [ID_OPLATA] int IDENTITY(1, 1) NOT NULL,
  [DATA] date NOT NULL,
  [ID_ZAKAZA] int NOT NULL,
  [ID_CUST] bigint NOT NULL,
  [ID_WORKER] int NOT NULL,
  [PRICE] int NOT NULL,
  PRIMARY KEY CLUSTERED ([ID_OPLATA])
)
ON [PRIMARY]
GO