CREATE TABLE [dbo].[UZAKAZ] (
  [ID_RESURCE] int IDENTITY(1, 1) NOT NULL,
  [ID_ZAKAZ] int NOT NULL,
  [ID_SCLAD] int NOT NULL,
  [COUNTS] int NULL,
  [ID_WORKER] int NULL,
  PRIMARY KEY CLUSTERED ([ID_RESURCE])
)
ON [PRIMARY]
GO